language: cpp
compiler:
  - gcc
  - clang

before_install:
  - echo 'yes' | sudo add-apt-repository ppa:mapnik/boost
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev

script: autoreconf --install --force && ./configure && make && make check
